name: Deploy Laravel 12

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Check PHP Version
      run: php -v

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Create .env file
      run: cp .env.example .env

    - name: Generate App Key
      run: php artisan key:generate

    - name: Execute Tests
      run: php artisan test

    - name: Deploy local
      run: |
        cd /var/www/html/cicd
        git pull origin main
        composer install --no-dev --optimize-autoloader
        php artisan migrate --force
        php artisan config:cache
        php artisan route:cache