name: Deploy Laravel 12

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Check PHP Version
      run: php -v

    - name: Bersihin Data Deploy
      run: |
        cd /var/www/html/cicd/Client
        rm -rf dist/*
        cd /var/www/html/cicd/Server/public
        rm -rf assets/*
        rm -f index.html
        rm -f vite.svg

    - name: Ke Directory Utama
      run: |
        cd /var/www/html/cicd
        git pull origin main

    - name: Build Vite Local
      run: |
        cd /var/www/html/cicd/Client
        npm install
        npm run build

    - name: Copy File Build Ke Laravel Local
      run: |
        cd /var/www/html/cicd/Client/dist
        mv -f ./* ../../Server/public/

    - name: Deploy Laravel Local
      run: |
        cd /var/www/html/cicd/Server
        composer install --no-dev --optimize-autoloader
        php artisan migrate --force
        php artisan optimize:clear
        php artisan config:cache
        php artisan route:cache