name: Deploy Laravel 12

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Check PHP Version
      run: php -v

    - name: Ke Directory Utama
      run: |
        cd /var/www/html/cicd
        git pull origin main

    - name: Build Vite Local
      run: |
        cd Client
        npm install
        npm run build

    - name: Copy File Build Ke Laravel Local
      run: |
        cd Client/dist
        mv ./* ../../Server/public/

    - name: Deploy Laravel Local
      run: |
        cd Server
        composer install --no-dev --optimize-autoloader
        php artisan migrate --force
        php artisan optimize:clear
        php artisan config:cache
        php artisan route:cache